services:
    - docker


before_install:
    - docker build -t ruffboy/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run ruffboy/react-test npm test -- --coverage

after_success:
    - docker build -t ruffboy/complex-client ./client
    - docker build -t ruffboy/complex-nginx ./nginx
    - docker build -t ruffboy/complex-server ./server
    - docker build -t ruffboy/complex-worker ./worker
    - echo "$docker_pass" | docker login -u "$docker_id" --password-stdin
    - docker push ruffboy/complex-client
    - docker push ruffboy/complex-nginx 
    - docker push ruffboy/complex-server
    - docker push ruffboy/complex-worker